name: twitch_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^2.2.0
  firebase_core: ^1.22.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.1.18
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.4
  file_picker: ^4.5.1
  permission_handler: ^10.0.1
  agora_rtc_engine: ^5.3.0
  http: ^0.13.5
 




  flutter: 
    sdk: flutter
  dotted_border: ^2.0.0+2
  uuid: ^3.0.6
  timeago: ^3.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

